pylint:
  stage: test
  image: python:3.8
  before_script:
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt
  script:
    - pylint *.py
pytest:
  stage: test
  image: python:3.8
  before_script:
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt
  script:
    - python -m pytest tests
